config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'pages#home'
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, except: [:index, :new, :create]
  resources :users, only: [:show]
  get '/search', to: 'restaurants#search'
end

app/views/pages/home.html.erb
<div class="main-banner">
  <h1 class="text-white text-center mt-5">Poutine Podium</h1>
  <p class="text-white text-center">Le site des connaisseurs de poutine.</p>

  <%= form_with(url: "/search", method: "get") do %>
    <div class="form-inline d-flex justify-content-center">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control w-50",
        placeholder: "Entrer une poutine, une ville..."
      %>
      <%= submit_tag "Trouver une poutinerie", class: "btn btn-main-action" %>
    </div>
  <% end %>

  <div class="d-flex align-items-center justify-content-center flex-column flex-sm-row my-4">
  </div>
</div>

<div class="container home">
  <div class="row">
    <div class="col-12 col-xl-8">
      <h2 class="text-center my-3">TOP 10 POUTINES</h2>
      <table class="table-podium table">
        <% @restaurants.take(9).each_with_index do |restaurant, i| %>
          <tr data-toggle="collapse" data-target="#collapse-<%= i %>" class="table-podium-header">
            <td class="d-none d-sm-block">
              <% if restaurant.photo.attached? %>
                <%= cl_image_tag restaurant.photo.key, class: "img-circle" %>
              <% else %>
                <%= image_tag 'https://previews.123rf.com/images/sudowoodo/sudowoodo1701/sudowoodo170100010/68834656-poutine-traditional-canadian-food-from-quebec-potato-french-fries-with-gravy-and-cheese-curds-isolat.jpg', class: "img-circle" %>
              <% end %>
            </td>
          <td>#<%= i + 1 %></td>
            <td class="w-100"><%= restaurant.name %></td>
            <td>
              <% unless restaurant.json_address.nil? %>
                <% if restaurant.json_address['data']['address']['city'].nil? %>
                  <%= restaurant.json_address['data']['address']['municipality'] %>
                <% else %>
                  <%= restaurant.json_address['data']['address']['city'] %>
                <% end %>
              <% end %>
            </td>
            <td>94%</td>
          </tr>
          <tr class="table-podium-body">
            <td colspan="12">
              <div class="collapse" id="collapse-<%= i %>">
                <div class="p-2">
                  <div class="d-flex justify-content-between">
                    <div>
                      <div class='misc-rating'>Frites: <%= '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe * 5 %></div>
                      <div class='misc-rating'>Sauce: <%= '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe * 4 %></div>
                      <div class='misc-rating'>Fromage: <%= '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe * 3 %></div>
                      <div class='misc-rating'>Service: <%= '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe * 5 %></div>
                    </div>
                    <div>
                      <div class='misc-rating'>Nombre d'avis: <%= restaurant.reviews.count %></div>
                      <div>Catégorie: <%= restaurant.restaurant_category.name %></div>
                      <div>Prix de la poutine classique: <%= restaurant.poutine_price %> $</div>
                      <div>Addresse: <%= restaurant.address %></div>
                    </div>
                  </div>

                  <div class="container-fluid my-3">
                    <div id="carousel-example-<%= i %>" class="carousel carousel-<%= i %> slide" data-interval="false" data-ride="carousel-example-<%= i %>">

                      <div class="carousel-inner c-<%= i %> row w-100 mx-auto" role="listbox">
                        <% restaurant.reviews.map{ |r| r.photos }.flatten.each_with_index do |photo, j| %>
                          <div class="carousel-item ci-<%= i %> col-12 col-sm-6 col-md-4 <%= 'active' if j == 0 %>">
                            <%= cl_image_tag photo.key, height: 160, width: 240, crop: :fill, class: "img-fluid mx-auto d-block carousel-img" %>
                          </div>
                        <% end %>
                      </div>

                      <a class="carousel-control-prev" href="#carousel-example-<%= i %>" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="carousel-control-next" href="#carousel-example-<%= i %>" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                    </div>
                    <%= link_to 'Voir le restaurant', restaurant_path(restaurant), class: "btn btn-main-action my-4" %>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-12 col-xl-4 mt-5 h-100">
      <div class="border m-3 p-4">
        <h2>Derniers avis</h2>
          <% Review.all.last(4).reverse.each do |review| %>
            <div class="card-review-small p-2 mb-3 border-bottom">
              <div><strong><%= review.restaurant.name %></strong>, par <%= review.user.first_name %>, </div>
              <p><%= truncate(review.body, :length => 200, :separator => '...') %></p>
              <%= link_to "lire l'avis complet", restaurant_path(review.restaurant) + '#' + review.id.to_s %>
            </div>
          <% end %>
        <p>Community stuff</p>
      </div>
    </div>
  </div>
</div>