config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'pages#home'
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :reviews, except: [:index, :new, :create]
  resources :users, only: [:show]
  get '/search', to: 'restaurants#search'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  searchkick

  has_many :reviews, dependent: :destroy
  belongs_to :restaurant_category
  belongs_to :user

  validates :address, presence: true
  validates :name, presence: true
  validates :restaurant_category_id, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_after_action :verify_policy_scoped, :only => [:index, :show, :search]
  skip_before_action :authenticate_user!, :only => [:index, :show, :search]

  def index
    if params[:query].present?
      @restaurants = Restaurant.global_search(params[:query])
    else
      @restaurants = Restaurant.all
    end

    @restaurants_sorted = @restaurants.sort_by{|restaurant| restaurant.reviews.map{ |r| zero_if_nan(r.global_rating) + zero_if_nan(r.fries_rating) + zero_if_nan(r.cheese_rating) + zero_if_nan(r.sauce_rating) + zero_if_nan(r.service_rating) }.sum / (restaurant.reviews.blank? ? 1 : restaurant.reviews.count) }.reverse

    respond_to do |format|
      format.html
      format.json { render json: { restaurants: @restaurants } }
    end

    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "restaurants/info_window", locals: { restaurant: restaurant })
      }
    end
  end

  def search
    Restaurant.reindex
    query = params[:query].presence || '*'

    p1 = params[:p1].present? ? [0, 6] : nil
    p2 = params[:p2].present? ? [6, 9] : nil
    p3 = params[:p3].present? ? [9, 1000] : nil
    range_creator = [p1, p2, p3].select{ |list| list != nil }.flatten
    range = range_creator.min()..range_creator.max()
    conditions = {
      poutine_price: range
    }

    @restaurants = Restaurant.search query, where: conditions
    authorize @restaurants

    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "restaurants/info_window", locals: { restaurant: restaurant })
      }
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @review = Review.new
    @reviews = @restaurant.reviews.sort_by{|r| r.upvotes}.reverse if @restaurant.reviews
    @restaurant_global_rating = avg_global_rating(@restaurant)
    @markers = [@restaurant].map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "restaurants/info_window", locals: { restaurant: restaurant })
      }
    end
    respond_to do |format|
      format.html
      format.json { render json: { upvotes: @restaurant.reviews.first.upvotes } }
    end

    if @restaurant.poutine_price < 6
      @price_symbol = '$'
    elsif @restaurant.poutine_price < 10
      @price_symbol = '$$'
    else
      @price_symbol = '$$$'
    end

    unless @restaurant.json_address.nil?
      if @restaurant.json_address['data']['address']['city'].nil?
        @restaurant_city = @restaurant.json_address['data']['address']['municipality']
      else
        @restaurant_city = @restaurant.json_address['data']['address']['city']
      end
    end
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    authorize @restaurant
    @restaurant.json_address =  Geocoder.search(@restaurant.address).first
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.json_address = Geocoder.search(restaurant_address_params['address']).first if @restaurant.json_address.nil?
    @restaurant.save
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.destroy
    redirect_to root_path
  end

  private

  def restaurant_address_params
    params.require(:restaurant).permit(:address)
  end

  def restaurant_params
    params.require(:restaurant).permit(:restaurant_id, :name, :category, :address, :poutine_price, :photo, :restaurant_category_id)
  end

  def zero_if_nan(x)
    x.class == Integer || x.class == Float ? x : 0
  end

  def search_params
    params.require(:restaurant).permit(:name)
  end

  def avg_global_rating(restaurant)
    if restaurant.reviews
      (restaurant.reviews.map{|r| r.global_rating}.sum / restaurant.reviews.count.to_f).round(1)
    else
      "No ratings yet"
    end
  end
  helper_method :avg_global_rating
  helper_method :zero_if_nan
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
  def ratingsData
    Restaurant.all.map do |restaurant|
      avg_global_rating = avg_of_children(restaurant, Review, 'global_rating')
      avg_service_rating = avg_of_children(restaurant, Review, 'service_rating')
      avg_fries_rating = avg_of_children(restaurant, Review, 'fries_rating')
      avg_sauce_rating = avg_of_children(restaurant, Review, 'sauce_rating')
      avg_cheese_rating =  avg_of_children(restaurant, Review, 'cheese_rating')
      [
        restaurant.name,
        {
          avg_global_rating: avg_global_rating,
          avg_service_rating: avg_service_rating,
          avg_fries_rating: avg_fries_rating,
          avg_sauce_rating: avg_sauce_rating,
          avg_cheese_rating: avg_cheese_rating,
          PS_rating: compute_PS_rating(avg_global_rating,
                                        avg_service_rating,
                                        avg_fries_rating,
                                        avg_sauce_rating,
                                        avg_cheese_rating,
                                        restaurant.poutine_price)
        }
      ]
    end.to_h
  end
  # private

  def avg_of_children(parent_instance, child_class, child_class_property)
    all_children_of_parent = ActiveRecord::Base.connection.execute("
      SELECT *
      FROM #{child_class.name.downcase.pluralize}
      JOIN #{parent_instance.class.name.downcase.pluralize}
      ON reviews.restaurant_id = restaurants.id
      WHERE #{parent_instance.class.name.downcase.pluralize}.name = '#{parent_instance.name.gsub("'", "\'\'")}'
      ").to_a
    unless all_children_of_parent.empty?
      all_children_of_parent.map{ |child| child[child_class_property]}.sum.to_f / all_children_of_parent.count
    end
    # else returns nil by default, which is what we want
  end

  def compute_PS_rating(global, service, fries, sauce, cheese, price)
    unless [global, service, fries, sauce, cheese, price].include?(nil)
      (global + service + fries + sauce + cheese - price) / 10
    end
  end
end

app/views/restaurants/_form.html.erb
<div class="form-new-restaurant">
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name, label: 'Nom du restaurant' %>
    <%= f.input :address, label: "Addresse du restaurant (doit apparaître dans l'autocomplete)", id: 'restaurant_address'%>
    <%= f.input :poutine_price, label: 'Prix de la poutine classique (avant taxes)', class: "" %>
    <%= f.association :restaurant_category, input_html: { class: "pretty-radio-buttons" }, include_hidden: false, as: :radio_buttons, label: 'Catégorie du restaurant)', class: "" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Soumettre le restaurant", class: "btn btn-primary" %>
    <%= link_to "Annuler", root_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/restaurants/_info_window.html.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>

app/views/restaurants/edit.html.erb
<h1>Edit this restaurant</h1>
<%= render partial: '/restaurants/form', restaurant: @restaurant %>

app/views/restaurants/new.html.erb
<h1 class="text-center my-4">Nouveau restaurant</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <%= render partial: '/restaurants/form' %>
    </div>
  </div>
</div>

app/views/restaurants/search.html.erb
<h1 class="text-center">Search restaurants</h1>

<div class="d-flex w-100">

  <div class="search-filters p-3 border-right">
      <%= form_with(url: "/search", method: "get") do %>
        <div class="form-inline">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Entrer quelque chose..."
          %>
          <%= submit_tag "Rechercher", class: "btn btn-main-action" %>
        </div>
        <div>
          <%= label_tag(:prix, "- de 6$") %>
          <%= check_box_tag 'p1', 'yes', true %>
        </div>
        <div>
          <%= label_tag(:prix, "6$ - 9$") %>
          <%= check_box_tag 'p2', 'yes', true %>
        <div>
        </div>
          <%= label_tag(:prix, "plus de 9$") %>
          <%= check_box_tag 'p3', 'yes', true %>
        </div>

        <%= range_field(:product, :discount, in: 1..100) %>
      <% end %>
  </div>

  <div class="search-results p-3">
    <% @restaurants.each do |restaurant| %>
      <%= link_to restaurant_path(restaurant) do %>
        <div class="my-3 border-bottom">
          <h2><%= restaurant.name %></h2>
          <p><%= restaurant.address %></p>
          <p><%= restaurant.restaurant_category.name %></p>
          <p><%= restaurant.poutine_price.round(2) %> $</p>
          <p><%= avg_global_rating(restaurant) %>/10</p>
          <% if restaurant.photo.attached? %>
            <%= cl_image_tag restaurant.photo.key, class: "img-circle" %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div id="map"
       style="height: 100vh; width: 30vw; position: sticky; top: 0; right: 0;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="banner-restaurant restaurant-show">
  <div class="banner-restaurant-photos">
    <div class="restaurant-photos-filter"></div>
    <button type="button" class="btn btn-onimage" data-toggle="modal" data-target="#exampleModalCenter">
      <i class="fas fa-camera"></i> Toutes les photos
    </button>
    <button type="button" class="btn btn-onimage-mobile" data-toggle="modal" data-target="#exampleModalCenter">
      <i class="fas fa-camera"></i>
    </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <div id="carouselExampleControls" class="carousel slide" interval="false" data-ride="carousel">
              <div class="carousel-inner">
                <% @restaurant.reviews.map{ |r| r.photos }.flatten.each_with_index do |photo, i| %>
                  <div class="carousel-item <%= 'active' if i == 0 %>">
                    <%= cl_image_tag photo.key, class: "d-block w-100" %>
                  </div>
                <% end %>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
          <div class="modal-footer justify-content-between">
            <p class="text-left">Photos de <%= @restaurant.name %> (<%= @restaurant.reviews.map{|r| r.photos}.flatten.count %>)</p>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Retour</button>
          </div>
        </div>
      </div>
    </div>
    <% if @restaurant.reviews.map{ |r| r.photos.all }.flatten.count > 2 %>
      <% @restaurant.reviews.map{ |r| r.photos.all }.flatten.take(3).each do |photo| %>
        <%= cl_image_tag photo.key, crop: :fill %>
      <% end %>
    <% elsif @restaurant.reviews.map{ |r| r.photos.all }.flatten.count == 2 %>
      <% @restaurant.reviews.map{ |r| r.photos.all }.flatten.take(3).each do |photo| %>
        <%= cl_image_tag photo.key, crop: :fill %>
      <% end %>
      <div class="banner-placeholder">
        <%= image_tag 'poutine_placeholder.png' %>
      </div>
    <% elsif @restaurant.reviews.map{ |r| r.photos.all }.flatten.count == 1 %>
      <% @restaurant.reviews.map{ |r| r.photos.all }.flatten.take(3).each do |photo| %>
        <%= cl_image_tag photo.key, crop: :fill %>
      <% end %>
      <div class="banner-placeholder">
        <%= image_tag 'poutine_placeholder.png' %>
      </div>
      <div class="banner-placeholder">
        <%= image_tag 'poutine_placeholder.png' %>
      </div>
    <% else %>
      <div class="banner-placeholder">
        <%= image_tag 'poutine_placeholder.png' %>
      </div>
      <div class="banner-placeholder">
        <%= image_tag 'poutine_placeholder.png' %>
      </div>
      <div class="banner-placeholder">
        <%= image_tag 'poutine_placeholder.png' %>
      </div>
    <% end %>
  </div>
  <div class="container-md">
    <div class="card-parallax">
      <h1><%= @restaurant.name %></h1>
      <span class="mr-2"><%= @restaurant.restaurant_category.name %> à <%= @restaurant_city %></span> • <span class="mx-2"><%= @price_symbol %></span> • <span class="mx-2"><%= @restaurant_global_rating %>/10 (<%= @restaurant.reviews.count %> avis)</span><br>
      <% if @restaurant.user == current_user %>
        <div>
          <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_restaurant_path(@restaurant) %>
          <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      <% end %>
      <div class="card-parallax-rank">
        #34 sur 219 poutineries
      </div>
    </div>
  </div>
</div>


<div class="container mt-4">
  <div class="row flex-row-reverse">
    <div class="col-12 col-lg-9">
      <div class="review-container">
        <div class="pl-4 border-bottom">
          <h2>Avis (<%= @restaurant.reviews.count %>)</h2>
          <% unless @restaurant.reviews.blank? %>
            <p class="text-secondary mt-3">Moyenne:

              <span
              class='global-rating'
              style='background-color:
                <% if @restaurant_global_rating < 5 %>
                  <%= "red" %>
                <% elsif @restaurant_global_rating < 7 %>
                  <%= 'orange' %>
                <% else %>
                  <%= 'green' %>
                <% end %>
              '><%= @restaurant_global_rating %>/10</span>

              <span class="text-secondary">Frites <i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></span>
              <span class="text-secondary">Fromage <i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></span>
              <span class="text-secondary">Sauce <i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></span>
              <span class="text-secondary">Service <i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></span>
            </p>
          <% end %>


          <form class="form-inline my-3">
            <label class="sr-only" for="inlineFormInputName2">Mot-clé</label>
            <input type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Mot-clé">

            <button type="submit" class="btn btn-secondary mb-2">Rechercher les avis</button>
          </form>

        </div>


        <% if @reviews.blank? %>
          <p>Sois la première personne à donner ton opinion sur leur poutine!</p>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="card-review" id=<%= review.id %>>
              <div class="container-md">
              <div class="row justify-content-center">
              <div data-id=<%= review.id %> class="col-3 col-md-2 card-review-info text-center <%= "card-review-info-personal" unless review.user == current_user %>">
                <div>
                  <% if review.user.photo.attached? %>
                    <%= cl_image_tag review.user.photo.key, class: "img-circle" %>
                  <% else %>
                    <%= image_tag 'person-placeholder.jpg', class: "img-circle" %>
                  <% end %>
                </div>
                <div>
                  <%= review.user.first_name %> <%= review.user.last_name %>
                </div>
                <div>
                  <%= review.user.reviews.count %> avis
                </div>

                <div class="upvote-section">

                    <div class="form-review-upvotes" id="upvotes-<%= review.id %>">
                      <%= simple_form_for(review, remote: true) do |f| %>
                        <%= f.input :irrelevant, collection: (1..1).to_a, selected: 1, input_html: {class:"d-none hidden"} %>
                        <%= f.hidden_field :up_enabled, value: 'true', id: 'upEnabled-' + review.id.to_s %>
                        <%= button_tag :submit,
                        class: "btn-vote btn-upvote",
                        name: "vote_type",
                        value: "upvote",
                        disabled: (true if review.user == current_user) do %>
                          <i class="fas fa-thumbs-up"></i>
                        <% end %>
                      <% end %>
                      <span class="no-upvotes"><%= review.upvotes %></span>
                      <%= simple_form_for(review, remote: true) do |f| %>
                        <%= f.hidden_field :down_enabled, value: 'true', id: 'downEnabled-' + review.id.to_s %>
                        <%= f.input :irrelevant, collection: (1..1).to_a, selected: 1, input_html: {class:"d-none hidden"} %>
                        <%= button_tag :submit,
                        class: "btn-vote btn-downvote",
                        name: "vote_type",
                        value: "downvote",
                        disabled: (true if review.user == current_user) do %>
                          <i class="fas fa-thumbs-down"></i>
                        <% end %>
                      <% end %>
                    </div>

                  </div>

                </div>
                  <div class="col-9 col-md-10 card-review-body">
                    <h3>

                      <span
                      class='global-rating'
                      style='background-color:
                        <% if review.global_rating < 5 %>
                          <%= "red" %>
                        <% elsif review.global_rating < 7 %>
                          <%= 'orange' %>
                        <% else %>
                          <%= 'green' %>
                        <% end %>
                      '><%= review.global_rating %>/10</span>

                      <%= review.title %>
                    </h3>
                    <p class="my-3">
                      <% if review.user == current_user %>
                        <span class="mr-2">
                          <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_review_path(review) %>
                          <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, review_path(review), method: :delete, data: { confirm: "Are you sure?" } %>
                        </span>
                      <% end %>
                      <span class="misc-ratings">
                        Publié le <%= review.created_at.to_s[0..10].gsub('-', '/') %>
                        - <span class='misc-rating'>Frites <%= '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe * review.fries_rating if review.fries_rating %></span>
                         - <span class='misc-rating'>Fromage <%= '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe * review.cheese_rating if review.cheese_rating %></span>
                         - <span class='misc-rating'>Sauce <%= '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe * review.sauce_rating if review.sauce_rating %></span>
                         - <span class='misc-rating'>Service <%= '<i class="fa fa-star" aria-hidden="true"></i>'.html_safe * review.service_rating if review.service_rating %></span>
                      </span>
                    </p>
                    <p>
                      <% if review.body.length >= 1000 %>
                        <span class="teaser">
                          <%= truncate(review.body, :length => 1000, :separator => ' ') %>
                        </span>
                        <span class="complete"><%= review.body %></span>
                        <span class="more">more...</span>
                      <% else %>
                        <span><%= review.body %></span>
                      <% end %>
                    </p>

                    <% if review.photos.count.odd?%>
                      <div class="review-photos review-photos-odd">
                        <% review.photos.each do |photo| %>
                          <div class="review-photo">
                            <%= cl_image_tag photo.key, height: 480, width: 640, crop: :fill %>
                          </div>
                        <% end %>
                      </div>
                    <% else  %>
                      <div class="review-photos review-photos-even">
                        <% review.photos.each do |photo| %>
                          <div class="review-photo">
                            <%= cl_image_tag photo.key, height: 480, width: 640, crop: :fill %>
                          </div>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>
      </div>
    <div class="col-12 col-lg-3">
      <div class="show-sidebar">
        <div class="p-3 border">
          <p><i class=" mr-2 fas fa-map-marker-alt"></i><%= @restaurant.address %></p>
          <p><i class=" mr-1 fas fa-phone"></i> (514) 449-5639 </p>
          <p><i class=" mr-2 fas fa-globe"></i><a href="www.google.com">Voir le site</a></p>
          <div id="map"
               style="flex-grow: 1; width: 100%; height: 200px;"
               data-markers="<%= @markers.to_json %>"
               data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
        <div class="p-3 mt-3 text-center card-side-info">
          <h5 class="text-black">Combien notes-tu cette poutine?</h5>
          <%= link_to 'Donne ton avis', new_restaurant_review_path(@restaurant, @review), class: "btn btn-main-action w-100" %>
        </div>
      </div>
    </div>
  </div>
</div>